apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: influxdb-storage
spec:
  resources:
    requests:
      storage: 20Gi
  volumeMode: Filesystem
  #storageClassName: managed-nfs-storage 
  accessModes:
    - ReadWriteOnce
